#############################################################################
# Makefile for building: juegal
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sat May 2 20:09:50 2015
# Project:  juegal.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile juegal.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT
CFLAGS        = -m64 -pipe -O2 -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -std=c++0x -O2 -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)   -lsfml-system -lsfml-graphics -lsfml-window -lsfml-audio 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Game.cpp \
		Resources.cpp \
		utils.cpp \
		Scene.cpp \
		Player.cpp \
		Tongue.cpp \
		Chameleon.cpp \
		Portada.cpp \
		Goal.cpp \
		IngameMenu.cpp \
		Menu.cpp \
		Button.cpp \
		readlevels.cpp \
		frases.cpp \
		Background.cpp 
OBJECTS       = main.o \
		Game.o \
		Resources.o \
		utils.o \
		Scene.o \
		Player.o \
		Tongue.o \
		Chameleon.o \
		Portada.o \
		Goal.o \
		IngameMenu.o \
		Menu.o \
		Button.o \
		readlevels.o \
		frases.o \
		Background.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		juegal.pro
QMAKE_TARGET  = juegal
DESTDIR       = 
TARGET        = juegal

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: juegal.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile juegal.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile juegal.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/juegal1.0.0 || $(MKDIR) .tmp/juegal1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/juegal1.0.0/ && (cd `dirname .tmp/juegal1.0.0` && $(TAR) juegal1.0.0.tar juegal1.0.0 && $(COMPRESS) juegal1.0.0.tar) && $(MOVE) `dirname .tmp/juegal1.0.0`/juegal1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/juegal1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp Menu.hpp \
		utils.hpp \
		Button.hpp \
		Scene.hpp \
		Goal.hpp \
		Game.hpp \
		Player.hpp \
		Chameleon.hpp \
		Tongue.hpp \
		IngameMenu.hpp \
		readlevels.hpp \
		Resources.hpp \
		Background.hpp \
		Portada.hpp \
		frases.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

Game.o: Game.cpp Game.hpp \
		utils.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Game.o Game.cpp

Resources.o: Resources.cpp Resources.hpp \
		utils.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Resources.o Resources.cpp

utils.o: utils.cpp utils.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utils.o utils.cpp

Scene.o: Scene.cpp Scene.hpp \
		Goal.hpp \
		utils.hpp \
		Game.hpp \
		Player.hpp \
		Chameleon.hpp \
		Tongue.hpp \
		IngameMenu.hpp \
		Button.hpp \
		readlevels.hpp \
		Resources.hpp \
		Background.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Scene.o Scene.cpp

Player.o: Player.cpp Player.hpp \
		utils.hpp \
		Resources.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Player.o Player.cpp

Tongue.o: Tongue.cpp Tongue.hpp \
		utils.hpp \
		Resources.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Tongue.o Tongue.cpp

Chameleon.o: Chameleon.cpp Chameleon.hpp \
		utils.hpp \
		Tongue.hpp \
		Resources.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Chameleon.o Chameleon.cpp

Portada.o: Portada.cpp Portada.hpp \
		utils.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Portada.o Portada.cpp

Goal.o: Goal.cpp Goal.hpp \
		utils.hpp \
		Resources.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Goal.o Goal.cpp

IngameMenu.o: IngameMenu.cpp IngameMenu.hpp \
		utils.hpp \
		Button.hpp \
		Resources.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IngameMenu.o IngameMenu.cpp

Menu.o: Menu.cpp Menu.hpp \
		utils.hpp \
		Button.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Menu.o Menu.cpp

Button.o: Button.cpp Button.hpp \
		utils.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Button.o Button.cpp

readlevels.o: readlevels.cpp readlevels.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o readlevels.o readlevels.cpp

frases.o: frases.cpp frases.hpp \
		Background.hpp \
		utils.hpp \
		Resources.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frases.o frases.cpp

Background.o: Background.cpp Background.hpp \
		utils.hpp \
		Resources.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Background.o Background.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

